### ISSUE TITLE
Not working with Rails 4.0.3 / Ruby 2.0.0p353 and...

### ISSUE THREAD

**Issue by cymen** [hsume2/browserify-rails#13]
I'm getting this error:

```
throw Error("BrowserifyRails::BrowserifyError: Error while running `/Users/cvig/dev/generic-project-name/rails-generic-project-name/./node_modules/.bin/browserify --list`:


events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Invalid non-string/buffer chunk
    at validChunk (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:165:14)
    at Transform.Writable.write (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:12)
    at write (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
    at flow (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
    at Transform.pipeOnReadable (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
    at Transform.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:430:10)
    at emitReadable (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:426:5)
    at readableAddChunk (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at Transform.Readable.push (/Users/cvig/dev/generic-project-name/rails-generic-project-name/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)

  (in /Users/cvig/dev/generic-project-name/rails-generic-project-name/app/assets/javascripts/myfile.js)")
```

I can log the chunk -- it's the part after `chunk:`:

```
TypeError: Invalid non-string/buffer chunk: {\"id\":\"/Users/cvig/dev/projectname/rails-projectname/app/assets/javascripts/fake_d054ac34.js\",\"source\":\"\\n\\n\\n\\n\\nvar x = require('./hi');\\nx();\\n\",\"deps\":{\"./hi\":\"/Users/cvig/dev/projectname/rails-projectname/app/assets/javascripts/hi.js\"},\"entry\":true}\n
```

package.json:

```
{
  "name": "myproject",
  "engines": {
    "node": ">= 0.10.0"
  },
  "devDependencies": {
    "grunt-jsbeautifier": "~0.2.6",
    "grunt-contrib-watch": "~0.5.3",
    "grunt": "~0.4.2",
    "grunt-prettysass": "~0.2.3",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-lintspaces": "~0.3.1",
    "grunt-contrib-jshint": "~0.8.0",
    "matchdep": "~0.3.0",
    "grunt-coffeelint": "0.0.8",
    "grunt-cli": "~0.1.13",
    "casperjs": "1.1.0-beta3",
    "browserify": "3.38.0",
    "watchify": "0.6.3",
    "prova": "1.0.12"
  },
  "scripts": {
    "bundle": "browserify app/assets/javascripts/myfile.js -o app/assets/javascripts/myfile-bundle.js",
    "watch": "watchify app/assets/javascripts/myfile.js -o app/assets/javascripts/myfile-bundle.js",
    "start": "npm run watch & rails s"
  }
}
```

$ node --version
v0.10.26

$ bundle exec rails -v
Rails 4.0.3

$ bundle exec ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.1.0]

$ npm list

```
designer@ /Users/cvig/dev/projectname/rails-projectname
├─┬ browserify@3.38.0
│ ├─┬ assert@1.1.1
│ │ └── util@0.10.2
│ ├─┬ browser-pack@2.0.1
│ │ ├─┬ combine-source-map@0.3.0
│ │ │ ├── convert-source-map@0.3.3
│ │ │ ├── inline-source-map@0.3.0
│ │ │ └─┬ source-map@0.1.33
│ │ │   └── amdefine@0.1.0
│ │ ├─┬ JSONStream@0.6.4
│ │ │ ├── jsonparse@0.0.5
│ │ │ └── through@2.2.7
│ │ └── through@2.3.4
│ ├─┬ browser-resolve@1.2.2
│ │ └── resolve@0.6.1
│ ├─┬ buffer@2.1.5
│ │ ├── base64-js@0.0.6
│ │ └── ieee754@1.1.3
│ ├── builtins@0.0.3
│ ├── commondir@0.0.1
│ ├─┬ concat-stream@1.4.4
│ │ ├─┬ readable-stream@1.1.12
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.25-1
│ │ └── typedarray@0.0.5
│ ├── console-browserify@1.0.3
│ ├── constants-browserify@0.0.1
│ ├── crypto-browserify@1.0.9
│ ├── deep-equal@0.1.2
│ ├── defined@0.0.0
│ ├─┬ deps-sort@0.1.1
│ │ ├─┬ JSONStream@0.6.4
│ │ │ ├── jsonparse@0.0.5
│ │ │ └── through@2.2.7
│ │ ├── minimist@0.0.8
│ │ └── through@2.3.4
│ ├─┬ derequire@0.8.0
│ │ ├── esprima-fb@3001.1.0-dev-harmony-fb
│ │ ├─┬ esrefactor@0.1.0
│ │ │ ├── escope@0.0.16
│ │ │ ├── esprima@1.0.4
│ │ │ └── estraverse@0.0.4
│ │ └── estraverse@1.5.0
│ ├── domain-browser@1.1.1
│ ├── duplexer@0.1.1
│ ├── events@1.0.0
│ ├─┬ glob@3.2.9
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├─┬ http-browserify@1.3.2
│ │ └── Base64@0.2.0
│ ├── https-browserify@0.0.0
│ ├── inherits@2.0.1
│ ├─┬ insert-module-globals@5.0.1
│ │ ├─┬ lexical-scope@1.1.0
│ │ │ └─┬ astw@1.1.0
│ │ │   └── esprima-fb@3001.1.0-dev-harmony-fb
│ │ ├── process@0.6.0
│ │ └── through@2.3.4
│ ├─┬ JSONStream@0.7.1
│ │ ├── jsonparse@0.0.5
│ │ └── through@2.2.7
│ ├─┬ module-deps@1.8.0
│ │ ├─┬ detective@3.1.0
│ │ │ ├─┬ escodegen@1.1.0
│ │ │ │ ├── esprima@1.0.4
│ │ │ │ ├── estraverse@1.5.0
│ │ │ │ ├── esutils@1.0.0
│ │ │ │ └─┬ source-map@0.1.33
│ │ │ │   └── amdefine@0.1.0
│ │ │ └── esprima-fb@3001.1.0-dev-harmony-fb
│ │ ├── minimist@0.0.8
│ │ └── through@2.3.4
│ ├── os-browserify@0.1.2
│ ├── parents@0.0.2
│ ├── path-browserify@0.0.0
│ ├── punycode@1.2.4
│ ├── querystring-es3@0.2.0
│ ├── resolve@0.6.2
│ ├── shallow-copy@0.0.1
│ ├── shell-quote@0.0.1
│ ├─┬ stream-browserify@0.1.3
│ │ └── process@0.5.2
│ ├── stream-combiner@0.0.4
│ ├── string_decoder@0.0.1
│ ├─┬ subarg@0.0.1
│ │ └── minimist@0.0.8
│ ├─┬ syntax-error@1.1.0
│ │ └── esprima-fb@3001.1.0-dev-harmony-fb
│ ├─┬ through2@0.4.1
│ │ ├─┬ readable-stream@1.0.26-4
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.25-1
│ │ └─┬ xtend@2.1.2
│ │   └── object-keys@0.4.0
│ ├─┬ timers-browserify@1.0.1
│ │ └── process@0.5.2
│ ├── tty-browserify@0.0.0
│ ├─┬ umd@2.0.0
│ │ ├─┬ rfile@1.0.0
│ │ │ ├── callsite@1.0.0
│ │ │ └── resolve@0.3.1
│ │ ├─┬ ruglify@1.0.0
│ │ │ └─┬ uglify-js@2.2.5
│ │ │   ├─┬ optimist@0.3.7
│ │ │   │ └── wordwrap@0.0.2
│ │ │   └─┬ source-map@0.1.33
│ │ │     └── amdefine@0.1.0
│ │ ├── through@2.3.4
│ │ └─┬ uglify-js@2.4.13
│ │   ├── async@0.2.10
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.2
│ │   ├─┬ source-map@0.1.33
│ │   │ └── amdefine@0.1.0
│ │   └── uglify-to-browserify@1.0.2
│ ├─┬ url@0.7.9
│ │ ├── punycode@1.0.0
│ │ └── querystring@0.1.0
│ ├── util@0.10.3
│ ├─┬ vm-browserify@0.0.4
│ │ └── indexof@0.0.1
│ └─┬ zlib-browserify@0.0.3
│   └─┬ tape@0.2.2
│     ├── deep-equal@0.0.0
│     └── jsonify@0.0.0
├─┬ casperjs@1.1.0-beta3
│ └─┬ phantomjs@1.9.7-3
│   ├── adm-zip@0.2.1
│   ├── kew@0.1.7
│   ├── mkdirp@0.3.5
│   ├── ncp@0.4.2
│   ├─┬ npmconf@0.0.24
│   │ ├─┬ config-chain@1.1.8
│   │ │ └── proto-list@1.2.2
│   │ ├── inherits@1.0.0
│   │ ├── ini@1.1.0
│   │ ├─┬ nopt@2.2.0
│   │ │ └── abbrev@1.0.4
│   │ ├── once@1.1.1
│   │ ├── osenv@0.0.3
│   │ └── semver@1.1.4
│   ├── rimraf@2.2.6
│   └── which@1.0.5
├─┬ grunt@0.4.4
│ ├── async@0.1.22
│ ├── coffee-script@1.3.3
│ ├── colors@0.6.2
│ ├── dateformat@1.0.2-1.2.3
│ ├── eventemitter2@0.4.13
│ ├── exit@0.1.2
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.9
│ │ │ └── inherits@2.0.1
│ │ └── lodash@2.4.1
│ ├── getobject@0.1.0
│ ├─┬ glob@3.1.21
│ │ ├── graceful-fs@1.2.3
│ │ └── inherits@1.0.0
│ ├── grunt-legacy-util@0.1.2
│ ├── hooker@0.2.3
│ ├── iconv-lite@0.2.11
│ ├─┬ js-yaml@2.0.5
│ │ ├─┬ argparse@0.1.15
│ │ │ ├── underscore@1.4.4
│ │ │ └── underscore.string@2.3.3
│ │ └── esprima@1.0.4
│ ├── lodash@0.9.2
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.5.0
│ │ └── sigmund@1.0.0
│ ├─┬ nopt@1.0.10
│ │ └── abbrev@1.0.4
│ ├── rimraf@2.2.6
│ ├── underscore.string@2.2.1
│ └── which@1.0.5
├─┬ grunt-cli@0.1.13
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.9
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.2.14
│ │ │   ├── lru-cache@2.5.0
│ │ │   └── sigmund@1.0.0
│ │ └── lodash@2.4.1
│ ├─┬ nopt@1.0.10
│ │ └── abbrev@1.0.4
│ └── resolve@0.3.1
├─┬ grunt-coffeelint@0.0.8
│ └─┬ coffeelint@1.0.8
│   ├── coffee-script@1.6.3
│   ├─┬ glob@3.2.9
│   │ ├── inherits@2.0.1
│   │ └─┬ minimatch@0.2.14
│   │   ├── lru-cache@2.5.0
│   │   └── sigmund@1.0.0
│   └─┬ optimist@0.6.1
│     ├── minimist@0.0.8
│     └── wordwrap@0.0.2
├── grunt-contrib-copy@0.5.0
├─┬ grunt-contrib-jshint@0.8.0
│ └─┬ jshint@2.4.4
│   ├─┬ cli@0.4.5
│   │ └─┬ glob@3.2.9
│   │   └── inherits@2.0.1
│   ├── console-browserify@0.1.6
│   ├── exit@0.1.2
│   ├─┬ htmlparser2@3.3.0
│   │ ├── domelementtype@1.1.1
│   │ ├── domhandler@2.1.0
│   │ ├── domutils@1.1.6
│   │ └─┬ readable-stream@1.0.26-4
│   │   ├── core-util-is@1.0.1
│   │   ├── inherits@2.0.1
│   │   ├── isarray@0.0.1
│   │   └── string_decoder@0.10.25-1
│   ├─┬ minimatch@0.2.14
│   │ ├── lru-cache@2.5.0
│   │ └── sigmund@1.0.0
│   ├── shelljs@0.1.4
│   └── underscore@1.4.4
├─┬ grunt-contrib-watch@0.5.3
│ ├─┬ gaze@0.4.3
│ │ └─┬ globule@0.1.0
│ │   ├─┬ glob@3.1.21
│ │   │ ├── graceful-fs@1.2.3
│ │   │ └── inherits@1.0.0
│ │   ├── lodash@1.0.1
│ │   └─┬ minimatch@0.2.14
│ │     ├── lru-cache@2.5.0
│ │     └── sigmund@1.0.0
│ └─┬ tiny-lr@0.0.4
│   ├── debug@0.7.4
│   ├── faye-websocket@0.4.4
│   ├─┬ noptify@0.0.3
│   │ └─┬ nopt@2.0.0
│   │   └── abbrev@1.0.4
│   └── qs@0.5.6
├─┬ grunt-jsbeautifier@0.2.6
│ ├─┬ js-beautify@1.4.2
│ │ ├─┬ config-chain@1.1.8
│ │ │ ├── ini@1.1.0
│ │ │ └── proto-list@1.2.2
│ │ ├── mkdirp@0.3.5
│ │ └─┬ nopt@2.1.2
│ │   └── abbrev@1.0.4
│ ├── lodash@2.4.1
│ └── underscore.string@2.3.3
├─┬ grunt-lintspaces@0.3.1
│ └─┬ editorconfig@0.11.4
│   ├─┬ commander@1.1.1
│   │ └── keypress@0.1.0
│   ├── lru-cache@2.0.4
│   └── sigmund@1.0.0
├── grunt-prettysass@0.2.3
├─┬ matchdep@0.3.0
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.9
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.2.14
│ │ │   ├── lru-cache@2.5.0
│ │ │   └── sigmund@1.0.0
│ │ └── lodash@2.4.1
│ ├─┬ globule@0.1.0
│ │ ├─┬ glob@3.1.21
│ │ │ ├── graceful-fs@1.2.3
│ │ │ └── inherits@1.0.0
│ │ ├── lodash@1.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├── resolve@0.5.1
│ └── stack-trace@0.0.7
├─┬ prova@1.0.12
│ ├─┬ bind-key@0.0.0
│ │ └─┬ keyname-of@0.0.0
│ │   └── keynames@0.0.0
│ ├─┬ browserify@3.32.1
│ │ ├─┬ assert@1.1.1
│ │ │ └── util@0.10.2
│ │ ├─┬ browser-pack@2.0.1
│ │ │ ├─┬ combine-source-map@0.3.0
│ │ │ │ ├── convert-source-map@0.3.3
│ │ │ │ ├── inline-source-map@0.3.0
│ │ │ │ └─┬ source-map@0.1.33
│ │ │ │   └── amdefine@0.1.0
│ │ │ └─┬ JSONStream@0.6.4
│ │ │   ├── jsonparse@0.0.5
│ │ │   └── through@2.2.7
│ │ ├─┬ browser-resolve@1.2.2
│ │ │ └── resolve@0.6.1
│ │ ├─┬ buffer@2.1.5
│ │ │ ├── base64-js@0.0.6
│ │ │ └── ieee754@1.1.3
│ │ ├── builtins@0.0.2
│ │ ├── commondir@0.0.1
│ │ ├── console-browserify@1.0.3
│ │ ├── constants-browserify@0.0.1
│ │ ├── crypto-browserify@1.0.9
│ │ ├── deep-equal@0.1.2
│ │ ├── defined@0.0.0
│ │ ├─┬ deps-sort@0.1.1
│ │ │ ├─┬ JSONStream@0.6.4
│ │ │ │ ├── jsonparse@0.0.5
│ │ │ │ └── through@2.2.7
│ │ │ └── minimist@0.0.8
│ │ ├─┬ derequire@0.6.1
│ │ │ ├── esprima-six@0.0.3
│ │ │ ├─┬ esrefactor@0.1.0
│ │ │ │ ├── escope@0.0.16
│ │ │ │ ├── esprima@1.0.4
│ │ │ │ └── estraverse@0.0.4
│ │ │ └── estraverse@1.5.0
│ │ ├── domain-browser@1.1.1
│ │ ├── duplexer@0.1.1
│ │ ├── events@1.0.0
│ │ ├─┬ http-browserify@1.3.2
│ │ │ └── Base64@0.2.0
│ │ ├── https-browserify@0.0.0
│ │ ├── inherits@2.0.1
│ │ ├─┬ insert-module-globals@3.2.0
│ │ │ ├─┬ lexical-scope@0.1.0
│ │ │ │ └─┬ astw@0.1.0
│ │ │ │   └── esprima-six@0.0.3
│ │ │ └── process@0.5.2
│ │ ├─┬ JSONStream@0.7.1
│ │ │ ├── jsonparse@0.0.5
│ │ │ └── through@2.2.7
│ │ ├─┬ module-deps@1.7.1
│ │ │ ├─┬ detective@2.4.1
│ │ │ │ ├─┬ escodegen@1.1.0
│ │ │ │ │ ├── esprima@1.0.4
│ │ │ │ │ ├── estraverse@1.5.0
│ │ │ │ │ ├── esutils@1.0.0
│ │ │ │ │ └─┬ source-map@0.1.33
│ │ │ │ │   └── amdefine@0.1.0
│ │ │ │ └── esprima-six@0.0.3
│ │ │ └── minimist@0.0.8
│ │ ├── os-browserify@0.1.2
│ │ ├── parents@0.0.2
│ │ ├── path-browserify@0.0.0
│ │ ├── punycode@1.2.4
│ │ ├── querystring-es3@0.2.0
│ │ ├── resolve@0.6.2
│ │ ├── shallow-copy@0.0.1
│ │ ├── shell-quote@0.0.1
│ │ ├─┬ stream-browserify@0.1.3
│ │ │ └── process@0.5.2
│ │ ├── stream-combiner@0.0.4
│ │ ├── string_decoder@0.0.1
│ │ ├─┬ subarg@0.0.1
│ │ │ └── minimist@0.0.8
│ │ ├─┬ syntax-error@0.1.0
│ │ │ └── esprima-six@0.0.3
│ │ ├─┬ timers-browserify@1.0.1
│ │ │ └── process@0.5.2
│ │ ├── tty-browserify@0.0.0
│ │ ├─┬ umd@2.0.0
│ │ │ ├─┬ rfile@1.0.0
│ │ │ │ ├── callsite@1.0.0
│ │ │ │ └── resolve@0.3.1
│ │ │ ├─┬ ruglify@1.0.0
│ │ │ │ └─┬ uglify-js@2.2.5
│ │ │ │   ├─┬ optimist@0.3.7
│ │ │ │   │ └── wordwrap@0.0.2
│ │ │ │   └─┬ source-map@0.1.33
│ │ │ │     └── amdefine@0.1.0
│ │ │ └─┬ uglify-js@2.4.13
│ │ │   ├── async@0.2.10
│ │ │   ├─┬ optimist@0.3.7
│ │ │   │ └── wordwrap@0.0.2
│ │ │   ├─┬ source-map@0.1.33
│ │ │   │ └── amdefine@0.1.0
│ │ │   └── uglify-to-browserify@1.0.2
│ │ ├─┬ url@0.7.9
│ │ │ ├── punycode@1.0.0
│ │ │ └── querystring@0.1.0
│ │ ├── util@0.10.3
│ │ ├─┬ vm-browserify@0.0.4
│ │ │ └── indexof@0.0.1
│ │ └─┬ zlib-browserify@0.0.3
│ │   └─┬ tape@0.2.2
│ │     ├── deep-equal@0.0.0
│ │     └── jsonify@0.0.0
│ ├─┬ concat-stream@1.4.4
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@1.1.12
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.25-1
│ │ └── typedarray@0.0.5
│ ├── default-debug@0.0.0
│ ├─┬ dom-children@0.0.2
│ │ └─┬ new-element@0.0.1
│ │   ├── domify@1.0.0
│ │   └── new-format@0.0.1
│ ├─┬ dom-classes@0.0.0
│ │ └── indexof@0.0.1
│ ├── escape-html@1.0.1
│ ├─┬ failing-code@0.0.2
│ │ └── failing-line@0.0.7
│ ├─┬ faye-websocket@0.7.2
│ │ └── websocket-driver@0.3.2
│ ├── filter-stack@0.0.0
│ ├── format-text@0.0.3
│ ├─┬ glob@3.2.9
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├── is-node@0.0.0
│ ├── left-pad@0.0.0
│ ├─┬ local-debug@0.0.0
│ │ └── debug@0.8.0
│ ├─┬ new-command@0.0.3
│ │ ├── minimist@0.0.8
│ │ ├─┬ show-help@1.0.0
│ │ │ └── first-val@0.0.0
│ │ └── show-version@1.0.0
│ ├── on-off@0.0.2
│ ├── prettify-error@0.0.2
│ ├── pubsub@1.0.2
│ ├── resumer@0.0.0
│ ├─┬ route-map@0.0.0
│ │ └── path-to-regexp@0.0.2
│ ├─┬ select-dom@0.0.0
│ │ └── qwery@3.4.2
│ ├─┬ stream-format@0.0.3
│ │ ├── new-format@0.0.1
│ │ ├── parallel-loop@0.0.0
│ │ └── pause-function@0.0.1
│ ├─┬ style-dom@0.0.0
│ │ └── to-camel-case@0.2.0
│ ├─┬ style-format@0.0.0
│ │ └── ansi-codes@0.0.1
│ ├─┬ tape@2.12.2
│ │ ├── deep-equal@0.2.1
│ │ ├── defined@0.0.0
│ │ ├── inherits@2.0.1
│ │ └── object-inspect@0.4.0
│ └── through@2.3.4
└─┬ watchify@0.6.3
  ├─┬ chokidar@0.8.2
  │ ├─┬ fsevents@0.2.0
  │ │ └── nan@0.8.0
  │ └── recursive-readdir@0.0.2
  ├─┬ optimist@0.5.2
  │ └── wordwrap@0.0.2
  ├── shallow-copy@0.0.1
  └── through@2.3.4
```

**Comment by cymen** [comment]
I dug into this some more... If I change `validChunk` by allow a chunk to be an object (just like the string check), everything works. So we're passing down the contents of the file we want to write to the filesystem as an object instead of a string. Going to go hunt that down.

**Comment by cymen** [comment]
I downgraded browserify node module to 3.33.1 and it works. So something is broken with current browserify node module (I looked closer at the code in this gem and it is clear that it is not the code in the gem).

**Comment by cymen** [comment]
Closing as solution is to use older version of browserify module.
